CREATE TABLE `ttl.GamesPlayers` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`PlayerAId`	INTEGER NOT NULL,
	`PlayerBId`	INTEGER NOT NULL,
	FOREIGN KEY(`PlayerBId`) REFERENCES `ttl.Players`(`Id`),
	FOREIGN KEY(`PlayerAId`) REFERENCES `ttl.Players`(`Id`)
);